[Demo]
host          = "clickhouse_clickhouse_1:9100"
database      = "default"
user          = "default"
password      = ""
message       = "hui"
table         = "HuiTable"
query         = "example_query_id"
